pool:
  name: SelfPc
steps:
- task: Bash@3
  displayName: 'Bash Script'
  inputs:
    targetType: filePath
    filePath: './$(Build.Repository.LocalPath)/ci/buildAndroid.sh'

# - task: AppCenterDistribute@1
#   displayName: 'Deploy Zombie_arm7.apk to App Center'
#   inputs:
#     serverEndpoint: AppCenter
#     appSlug: legolasmuradin/ZombieAndroid
#     appFile: '$(Build.ArtifactStagingDirectory)/Zombie.apk/Shadow Knight.armeabi-v7a.apk'
#     symbolsIncludeParentDirectory: false
#     releaseNotesOption: file
#     releaseNotesFile: '$(Build.Repository.LocalPath)/changelog.txt'

# - task: AppCenterDistribute@1
#   displayName: 'Deploy Zombie_arm64.apk to App Center'
#   inputs:
#     serverEndpoint: AppCenter
#     appSlug: legolasmuradin/ZombieAndroidArm64
#     appFile: '$(Build.ArtifactStagingDirectory)/Zombie.apk/Shadow Knight.arm64-v8a.apk'
#     symbolsIncludeParentDirectory: false
#     releaseNotesOption: file
#     releaseNotesFile: '$(Build.Repository.LocalPath)/changelog.txt'

# - task: AppCenterDistribute@1
#   displayName: 'Deploy Zombie_x86.apk to App Center'
#   inputs:
#     serverEndpoint: AppCenter
#     appSlug: legolasmuradin/ZombieAndroidx86
#     appFile: '$(Build.ArtifactStagingDirectory)/Zombie.apk/Shadow Knight.x86.apk'
#     symbolsIncludeParentDirectory: false
#     releaseNotesOption: file
#     releaseNotesFile: '$(Build.Repository.LocalPath)/changelog.txt'

